/*
 * JDBCTester.java
 *
 * Created on September 9, 2005, 8:38 PM
 */

/**
 *
 * @author  Omkar
 */
import java.sql.*;
import java.util.*;
class JDBCTester extends javax.swing.JDialog {
    
    /** Creates new form JDBCTester */
    public static String DRIVER;
    public static String DATA_SOURCE_NAME;
    public static String CONNECTION;
    public static boolean REQUIRES_AUTHENTICATION;
    public static String USERNAME;
    public static String PASSWORD;
    public java.awt.Frame parent;
    public JDBCTester(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setSize(402,398);
        setLocation(200,200);
}
    public JDBCTester()
    {
        dispose();
        new JDBCTester(new javax.swing.JFrame(), true).show();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dsn = new javax.swing.JTextField();
        driver = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        con = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        usr = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pwd = new javax.swing.JPasswordField();
        submit = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jLabel1.setText("DataBase Connectivity Testing Tool");
        jLabel1.setAutoscrolls(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 390, 28);

        jLabel2.setText("     Data Source Name : ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 50, 130, 14);

        dsn.setToolTipText("Enter the DSN of the database here");
        dsn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dsnFocusLost(evt);
            }
        });

        getContentPane().add(dsn);
        dsn.setBounds(130, 50, 240, 20);

        driver.setText("oracle.jdbc.driver.OracleDriver");
        driver.setToolTipText("Eg. oracle.jdbc.driver.OracleDriver");
        getContentPane().add(driver);
        driver.setBounds(130, 80, 240, 20);

        jLabel3.setText("Driver Name : ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 80, 80, 14);

        getContentPane().add(con);
        con.setText("jdbc:oracle:thin:@localhost:1521:xe");
        con.setToolTipText("1. oracle is the database used\n2.localhost is the IP Address where database is stored\n3.1521 is the port number and xe is the service provider");
        con.setBounds(130, 110, 240, 20);

        jLabel8.setText(" Connection :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 110, 80, 14);

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Requires Authentication");
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });

        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(130, 150, 180, 23);

        getContentPane().add(usr);
        usr.setBounds(130, 180, 240, 20);

        jLabel5.setText(" User Name :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 180, 80, 14);

        jLabel6.setText("Password  :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 220, 70, 14);

        getContentPane().add(pwd);
        pwd.setBounds(130, 220, 240, 20);

        submit.setFont(new java.awt.Font("Arial Black", 0, 14));
        submit.setText("BACK<<<");
        submit.setDefaultCapable(false);
        submit.setFocusTraversalPolicyProvider(true);
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        submit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                submitKeyPressed(evt);
            }
        });

        getContentPane().add(submit);
        submit.setBounds(150, 260, 130, 31);

        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 300, 400, 10);

        jLabel9.setFont(new java.awt.Font("Bookman Old Style", 3, 18));
        //jLabel9.setText("OmDev Softwares Pvt. Ltd.");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 320, 360, 22);

        pack();
    }//GEN-END:initComponents

    private void submitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_submitKeyPressed
        if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_ENTER)
        {
            setParameters();
        }
    }//GEN-LAST:event_submitKeyPressed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        setParameters();
    }//GEN-LAST:event_submitActionPerformed
    public void setParameters()
    {
        DRIVER = driver.getText();
        DATA_SOURCE_NAME = dsn.getText();
        CONNECTION = con.getText();
        if(jCheckBox1.isSelected())
            REQUIRES_AUTHENTICATION = true;
        else
            REQUIRES_AUTHENTICATION = false;
        if(REQUIRES_AUTHENTICATION)
        {
            USERNAME = usr.getText();
            PASSWORD = pwd.getText();
        }
        else
        {
            USERNAME = "AUTHENTICATION NOT REQUIRED";
            PASSWORD = "AUTHENTICATION NOT REQUIRED";
        }
        afterParametersSet();
    }
    public void afterParametersSet()
    {
        dispose();
    }
    private void dsnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dsnFocusLost
        con.setText("jdbc:odbc:"+dsn.getText());
    }//GEN-LAST:event_dsnFocusLost

    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1ItemStateChanged
        if(jCheckBox1.isSelected())
        {
            usr.setEnabled(true);
            pwd.setEnabled(true);
        }
        else
        {
            usr.setEnabled(false);
            pwd.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBox1ItemStateChanged
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new JDBCTester(new javax.swing.JFrame(), true).show();
        //new JDBCTester().show();
    } 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField con;
    private javax.swing.JTextField driver;
    private javax.swing.JTextField dsn;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField pwd;
    private javax.swing.JButton submit;
    private javax.swing.JTextField usr;
    // End of variables declaration//GEN-END:variables
    
}
